version: 2.1

jobs:
  build:
    docker:
      - image: afonsoaugusto/base-ci:71dc2c7-master
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            make deploy

workflows:
  workflow:
    jobs:
      - build:
          context: CI
          filters:
            branches:
              only: main